'''
Author: Berdal, Ole
Created: 25.09.2018
Version: Python 3.7.0

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
import time
start_time = time.time()

fib = [1, 2]

next = fib[-2] + fib[-1]
while next <= 4000000:
    fib.append(next)
    next = fib[-2] + fib[-1]

remove_odd = [x for x in fib if not x % 2]
sum = sum(remove_odd)

print("Solution: %s.\nExecution time: %s seconds." % (sum, time.time() - start_time))