"""
Author: Berdal, Ole
Created: 18.01.2019
Version: Python 3.7.0

https://projecteuler.net/problem=12:
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1, 3
 6: 1, 2, 3, 6
10: 1, 2, 5, 10
15: 1, 3, 5, 15
21: 1, 3, 7, 21
28: 1, 2, 4, 7, 14, 28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import time
start_time = time.time()


def find_triangle_number_with_at_least_number_of_divisors(at_least_divisors):
    divisors_a = 1
    n = 2
    divisors_b = number_of_divisors(n)

    while divisors_a * divisors_b <= at_least_divisors:
        divisors_a = divisors_b
        n += 1
        divisors_b = number_of_divisors(n)

    return ((n - 1) * n) // 2


def number_of_divisors(number):
    if not number % 2:
        number //= 2

    primes = reduce_to_primes(number)

    divisor = 1
    for prime in primes:
        divisor *= prime + 1

    return divisor


def reduce_to_primes(n, start=3):
    start = 2 if not n % 2 else start
    bound = int(n**0.5) + 1
    step = 1 if not n % 2 else 2
    prime_factors = []
    for x in range(start, bound, step):
        if not n % x:
            n //= x
            prime_factors.append(1)
            while not n % x:
                n //= x
                prime_factors[-1] += 1
            return prime_factors + reduce_to_primes(n, x + 1 + x % 2)
    else:
        return [1] if n > 1 else []


def main():
    solution = find_triangle_number_with_at_least_number_of_divisors(500)

    print('Solution: %s.\nExecution time: %s seconds.' % (solution, time.time() - start_time))


if __name__ == '__main__':
    main()
