"""
Author: Berdal, Ole
Created: 18.01.2019
Edited: 03.10.2019
Version: Python 3.7.4

https://projecteuler.net/problem=12:
The sequence of triangle numbers is generated by adding the natural numbers. So the 7ᵗʰ triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1, 3
 6: 1, 2, 3, 6
10: 1, 2, 5, 10
15: 1, 3, 5, 15
21: 1, 3, 7, 21
28: 1, 2, 4, 7, 14, 28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import time
start_time = time.time()


def find_triangle_number_with_at_least_number_of_divisors(n_divisors):
    n = 2
    divisors_a, divisors_b = 1, number_of_divisors(number=n)

    while divisors_a * divisors_b <= n_divisors:
        n += 1
        divisors_a, divisors_b = divisors_b, number_of_divisors(number=n)

    return ((n - 1) * n) // 2


def number_of_divisors(number):
    if not number % 2:
        number //= 2

    divisor = 1
    for prime in reduce_to_primes(number=number):
        divisor *= prime

    return divisor


def reduce_to_primes(number, start=3):
    start = 2 if not number % 2 else start
    bound = int(number**0.5) + 1
    step = 1 if not number % 2 else 2
    prime_factors = []
    for x in range(start, bound, step):
        if not number % x:
            number //= x
            prime_factors.append(2)
            while not number % x:
                number //= x
                prime_factors[-1] += 1
            return prime_factors + reduce_to_primes(number=number, start=x + 1 + x % 2)
    else:
        return [2] if number > 1 else []


def main():
    solution = find_triangle_number_with_at_least_number_of_divisors(n_divisors=5 * 10**2)

    print('Solution: %s.\nExecution time: %s seconds.' % (solution, time.time() - start_time))


if __name__ == '__main__':
    main()
